/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.io.IOException;
import java.util.*;

import java.sql.*;

class Province {
    String id;
    String name;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

class City {
    String pid;
    String code;
    String name;

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }
    
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

interface ProvDao {
    Province findById(String id);   //通过id找到province

}

class PlainProvDao implements ProvDao {
    static {
        try{
            Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException ex) {
        } 
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(
            "jdbc:postgresql://localhost:5432/shop",
            "hjh", "1234");
    }

    private void closeConnection(Connection connection) {
        if(connection == null) {
            return;
        }
        try {
            connection.close();
        } catch (SQLException ex) {
        }
    }

    @Override
    public Province findById(String id) {
        Province p = new Province();
        Connection connection = null;
        try {
            connection = getConnection();
            PreparedStatement pstmt = connection.prepareStatement("select name from province where id = ?");
            pstmt.setString(1, id);

            ResultSet result = pstmt.executeQuery();

            if (result.next()) {
                String name = result.getString("name");

                p.setId(id);
                p.setName(name);

            }
            pstmt.close();
        } catch (SQLException ex) {
        } finally{
            closeConnection(connection);
        }
        return p;
    }
}


public class App {
    private static ProvDao provDao = new PlainProvDao();

    public static void main(String[] args) throws IOException {
        Province p = provDao.findById("16");
        System.out.println(p.name);
    }
}
