/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Weather02;

import java.util.List;
import java.io.IOException;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

import com.google.gson.Gson;

class Weather {
    String time;
    CityInfo cityInfo; 
    String date;
    String message;
    int status;
    Data data;

    public String toString() {
        return "time:" + this.time + "\n" + "message:" + this.message + "\n" + "city:" + this.cityInfo.city +
         "\n" + "yesterday:" + this.data.yesterday.date + "\n" + "tomorrow:" + this.data.forecast.get(1).sunrise; 
    }
} 

class CityInfo {
    String city;
    String cityId;
    String parent;
    String updateTime;
}

class Data {
    String shidu;
    double pm25;
    double pm10;
    String quality;
    String wendu;
    String ganmao;

    Everyday yesterday;
    List<Everyday> forecast;
}

class Everyday {
    String date;
    String sunrise;
    String high;
    String low;
    String sunset;
    double aqi;
    String ymd;
    String week;
    String fx;
    String fl;
    String type;
    String notice;
}

public class App {
    OkHttpClient client = new OkHttpClient();

    String run(String url) throws IOException {
        Request request = new Request.Builder()
            .url(url)
            .build();

        try (Response response = client.newCall(request).execute()) {
            return response.body().string();
        }
    }

    public static void main(String[] args) {
        try {
            App app = new App();
            String response = app.run("http://t.weather.sojson.com/api/weather/city/101240101");
            //System.out.println(response);
            Gson gson = new Gson();
            Weather w = gson.fromJson(response, Weather.class);
            System.out.println(w);
        } catch(IOException e) {
            System.out.println("io error");
        }
    }
}
