/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import com.google.common.base.Charsets;
import com.google.common.io.Files;
import java.io.File;
import java.io.IOException;
import java.util.*;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.sql.*;

class Place {
    int _id;
    int id;
    int pid;
    String city_code;
    String city_name;

    @Override
    public String toString() {
        return "city_code:" + this.city_code + " " + "city_name:" + this.city_name;
    }
}

public class App {

    public static void main(String[] args) throws IOException {

        Gson gson = new GsonBuilder().create();

        Map<Place, List<Place>> cmap = new HashMap<>();

        String fileName = "./_city.json";

        List<Place> provinces = new ArrayList<>();
        

        String content = Files.toString(new File(fileName), Charsets.UTF_8);

        Place[] places = gson.fromJson(content, Place[].class);
        
        Arrays.stream(places).forEach( e -> {
            if (e.pid == 0) {
                provinces.add(e);
            }
        });
        System.out.println(provinces);

        for (Place p : provinces) {
            List<Place> cities = new ArrayList<>();
            for (int i=0; i<places.length; i++) {
                if (places[i].pid == p.id) {
                    cities.add(places[i]);
                }
            }
            cmap.put(p, cities);
        }
        // System.out.println(cmap);

        try{
        Class.forName("org.postgresql.Driver");
		String url="jdbc:postgresql://localhost:5432;databaseName=shop";
		String user = "hjh";
		String pwd = "1234";
		Connection con = DriverManager.getConnection(url, user, pwd);
        con.setAutoCommit(false);

	
		Statement st = con.createStatement();
		String sql;
        for(int i=0; i < provinces.size(); i++) {
            sql = String.format("insert into province(id, name) values (%s, %s)" , "provinces[i][0]");
		    st.executeUpdate(sql);  //执行传入的sql语句
            // ResultSet rs = st.executeQuery(sql);
        }
        con.commit();
        }
        catch(Exception e){
			e.printStackTrace();
		}
    }
}