/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Weather;

import java.util.*;

import java.io.IOException;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

import com.google.gson.Gson;

class Weather {
    String time;
    CityInfo cityInfo; 
    String date;
    String message;
    int status;
    Data data;

    public String toString() {
        return "time:" + this.time + "\n" + "message:" + this.message + "\n" + "city:" + this.cityInfo.city +
         "\n" + "yesterday:" + this.data.yesterday.date + "\n" + "tomorrow:" + this.data.forecast.get(1).sunrise; 
    }
} 

class CityInfo {
    String city;
    String cityId;
    String parent;
    String updateTime;
}

class Data {
    String shidu;
    double pm25;
    double pm10;
    String quality;
    String wendu;
    String ganmao;

    Everyday yesterday;
    List<Everyday> forecast;
}

class Everyday {
    String date;
    String sunrise;
    String high;
    String low;
    String sunset;
    double aqi;
    String ymd;
    String week;
    String fx;
    String fl;
    String type;
    String notice;
}

public class App {
    OkHttpClient client = new OkHttpClient();;
    Queue<String> queue = new LinkedList<String>();

    class MyThread extends Thread {
        String url;
        String cityname;
        public MyThread(String cityname, String url) {
            this.cityname = cityname;
            this.url = url;
        }

        public String getCityName() {
            return this.cityname;
        }

        @Override
        public void run() {
            try {
                System.out.println(this.cityname);
                String x = visit(this.url);
                queue.offer(x);
            } catch (IOException e) {
            }
        }
    }


    public String visit(String url) throws IOException {
        Request request = new Request.Builder()
            .url(url)
            .build();

        try (Response response = this.client.newCall(request).execute()) {
            return response.body().string();
        }
    }

    public HashMap<String, String> initData() {
        HashMap<String, String> map = new HashMap<String, String>();    
        map.put("天津", "101030100");
        map.put("南昌", "101240101");
        map.put("北京", "101010100");
        map.put("上海", "101020100");
        map.put("香港", "101320101");
        map.put("澳门", "101330101");
        map.put("杭州", "101210101");
        map.put("苏州", "101190401");
        map.put("南京", "101190101");

        return map;
    }

    public List<String> getResults(HashMap<String, String> hmap) throws IOException, InterruptedException {
        List<String> al = new ArrayList<String>(); 
        List<MyThread> results = new ArrayList<MyThread>();

        for (Map.Entry<String, String> me : hmap.entrySet()) {
            MyThread t = new MyThread(me.getKey(), this.getUrl(me.getValue()));
            t.start();
            results.add(t);
        }

        for (MyThread x : results) {
            x.join();
        }

        while (queue.peek() != null) {
            al.add(queue.poll());
        }
        return al;
    }

    public String getUrl(String citycode) {
        String s = "http://t.weather.sojson.com/api/weather/city/%s";
        String url = String.format(s, citycode);
        return url;
    }

    class Result {

        public static Weather deal(String jsonStr) {
            Gson gson = new Gson();
            Weather w = gson.fromJson(jsonStr, Weather.class);
            return w;
        }

        public static List<Weather> dealList(List<String> jsonList) {
            List<Weather> wlist;
            Weather w;
            for(String s: jsonList) {
                w = this.deal(s);
                wlist.add(w);
            }
            return wlist;
        }
    }

    public static void main(String[] args) {
        List<Weather> wlist;
        App app = new App();
        HashMap<String, String> hmap = app.initData();
        List<String> jsonList;
        
        try {
            //System.out.println(app.getResults(hmap));
            jsonList = app.getResults(hmap);
            wlist = Result.dealList(jsonList);
            for (Weather w: wlist) {
                //Weather中toString()是覆盖重载了
                System.out.println(w);
            }
        } catch (IOException e) {
        } catch (InterruptedException e) {
        }
   }
}



